export const SITE_CONFIG = {
  name: "Dr. Lal PathLabs - Patient Service Centre",
  shortName: "Dr. Lal PathLabs",
  description: "Trusted diagnostic services in Lucknow. Quality pathology services with NABL accreditation. Home sample collection available.",
  phone: "+91 9451155402",
  whatsapp: "+91 9451155402",
  address: "Khargapur, Gomti Nagar, Lucknow, Uttar Pradesh 226010",
  mapsUrl: "https://www.google.com/maps/place/Dr+Lal+PathLabs+-+Patient+Service+Centre/@26.8361308,81.0175985,17z/data=!4m6!3m5!1s0x399be3aa699caec7:0x3d2045fc59c06a4e!8m2!3d26.8361261!4d81.0224694!16s%2Fg%2F11sssm62vw",
  mapsEmbed: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3558.8777034853646!2d81.0224694!3d26.8361261!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x399be3aa699caec7%3A0x3d2045fc59c06a4e!2sDr%20Lal%20PathLabs%20-%20Patient%20Service%20Centre!5e0!3m2!1sen!2sin!4v1699900000000!5m2!1sen!2sin",
  directionsUrl: "https://www.google.com/maps/dir/?api=1&destination=Dr+Lal+PathLabs+-+Patient+Service+Centre,+Lucknow",
} as const;

export const NAV_LINKS = [
  { href: "/", label: "Home" },
  { href: "/about", label: "About" },
  { href: "/tests", label: "Tests" },
  { href: "/health-packages", label: "Health Packages" },
  { href: "/home-collection", label: "Home Collection" },
  { href: "/book-test", label: "Book Test" },
  { href: "https://www.lalpathlabs.com/download-report", label: "Download Report" },
  { href: "/contact", label: "Contact" },
] as const;

export const POPULAR_TESTS = [
  {
    id: 1,
    name: "Complete Blood Count (CBC)",
    slug: "complete-blood-count-cbc",
    description: "Comprehensive blood test to evaluate overall health and detect disorders.",
    price: 210,
    originalPrice: 350,
    category: "Hematology",
    fasting: false,
    duration: "24 hours",
    parameters: "28+ parameters",
    popular: true,
  },
  {
    id: 2,
    name: "Blood Sugar (Fasting)",
    slug: "glucose-fasting-f",
    description: "Measures glucose levels after overnight fasting for diabetes screening.",
    price: 50,
    originalPrice: 100,
    category: "Diabetes",
    fasting: true,
    duration: "Same day",
    parameters: "Glucose",
    popular: true,
  },
  {
    id: 3,
    name: "HbA1c (Glycated Hemoglobin)",
    slug: "hba1c-glycosylated-hemoglobin",
    description: "Measures average blood sugar levels over the past 2-3 months.",
    price: 400,
    originalPrice: 550,
    category: "Diabetes",
    fasting: false,
    duration: "24 hours",
    parameters: "HbA1c %",
    popular: true,
  },
  {
    id: 4,
    name: "Liver Function Test (LFT)",
    slug: "liver-panel-1-lft",
    description: "Evaluates liver health by measuring enzymes, proteins, and bilirubin.",
    price: 600,
    originalPrice: 800,
    category: "Liver",
    fasting: true,
    duration: "24 hours",
    parameters: "11 parameters",
    popular: true,
  },
  {
    id: 5,
    name: "Kidney Function Test (KFT)",
    slug: "kidney-panel-kft",
    description: "Assesses kidney function through urea, creatinine, and electrolytes.",
    price: 630,
    originalPrice: 800,
    category: "Kidney",
    fasting: true,
    duration: "24 hours",
    parameters: "14 parameters",
    popular: true,
  },
  {
    id: 6,
    name: "Lipid Profile",
    slug: "lipid-profile-complete",
    description: "Measures cholesterol and triglycerides to assess heart health risk.",
    price: 350,
    originalPrice: 500,
    category: "Cardiac",
    fasting: true,
    duration: "24 hours",
    parameters: "9 parameters",
    popular: true,
  },
  {
    id: 7,
    name: "Thyroid Profile (T3, T4, TSH)",
    slug: "thyroid-profile-total",
    description: "Evaluates thyroid gland function and hormone levels.",
    price: 600,
    originalPrice: 750,
    category: "Thyroid",
    fasting: false,
    duration: "24 hours",
    parameters: "T3, T4, TSH",
    popular: true,
  },
  {
    id: 8,
    name: "Vitamin D Total",
    slug: "vitamin-d-25-hydroxy",
    description: "Measures vitamin D levels for bone health and immunity assessment.",
    price: 800,
    originalPrice: 1000,
    category: "Vitamins",
    fasting: false,
    duration: "24 hours",
    parameters: "25-OH Vitamin D",
    popular: true,
  },
  {
    id: 9,
    name: "Vitamin B12",
    slug: "vitamin-b12-cyanocobala-min",
    description: "Evaluates vitamin B12 levels for nerve function and anemia screening.",
    price: 650,
    originalPrice: 800,
    category: "Vitamins",
    fasting: false,
    duration: "24 hours",
    parameters: "Vitamin B12",
    popular: true,
  },
  {
    id: 10,
    name: "Dengue Profile",
    slug: "dengue-fever-combined-panel",
    description: "Comprehensive test for dengue fever diagnosis including NS1 and antibodies.",
    price: 1200,
    originalPrice: 1500,
    category: "Infectious",
    fasting: false,
    duration: "Same day",
    parameters: "NS1, IgG, IgM",
    popular: true,
  },
  {
    id: 11,
    name: "Malaria Antigen",
    slug: "malaria-vivax-and-falciparum-antigen",
    description: "Detects malaria parasites through rapid antigen testing.",
    price: 400,
    originalPrice: 500,
    category: "Infectious",
    fasting: false,
    duration: "Same day",
    parameters: "Malaria antigen",
    popular: true,
  },
  {
    id: 12,
    name: "Typhoid Test (Widal)",
    slug: "widal-slide-agglutinatio-n-test",
    description: "Diagnoses typhoid fever through antibody detection.",
    price: 350,
    originalPrice: 450,
    category: "Infectious",
    fasting: false,
    duration: "Same day",
    parameters: "Widal",
    popular: true,
  },
  {
    id: 13,
    name: "Pregnancy Test (Beta HCG)",
    slug: "hcg-beta-total-quantitative-tumor-marker",
    description: "Confirms pregnancy through HCG hormone detection in blood.",
    price: 690,
    originalPrice: 800,
    category: "Women's Health",
    fasting: false,
    duration: "Same day",
    parameters: "Beta HCG",
    popular: true,
  },
  {
    id: 14,
    name: "Urine Routine & Microscopy",
    slug: "urine-examination-routine-urine-r-e",
    description: "Analyzes urine for infections, kidney issues, and metabolic disorders.",
    price: 200,
    originalPrice: 300,
    category: "Urinary",
    fasting: false,
    duration: "Same day",
    parameters: "20+ parameters",
    popular: true,
  },
  {
    id: 15,
    name: "Stool Routine",
    slug: "stool-examination-routine-stool-r-e",
    description: "Examines stool for digestive disorders and parasitic infections.",
    price: 250,
    originalPrice: 350,
    category: "Digestive",
    fasting: false,
    duration: "Same day",
    parameters: "Routine examination",
    popular: true,
  },
  {
    id: 16,
    name: "Full Body Checkup",
    slug: "full-body-checkup",
    description: "Comprehensive health screening with 80+ tests for overall wellness.",
    price: 2499,
    originalPrice: 3500,
    category: "Health Checkup",
    fasting: true,
    duration: "48 hours",
    parameters: "80+ tests",
    popular: true,
  },
] as const;

export const HEALTH_PACKAGES = [
  {
    id: 1,
    name: "Super 1",
    slug: "super-1",
    description: "Essential health screening package covering key blood and metabolic tests.",
    price: 1250,
    originalPrice: 1800,
    tests: ["CBC", "Blood Sugar Fasting", "Lipid Profile", "Urine Routine", "Liver Function", "KFT"],
    testsCount: 40,
    idealFor: "Adults 18–40 years",
    fasting: true,
    reportsIn: "24–48 hours",
    popular: false,
  },
  {
    id: 2,
    name: "Super 2",
    slug: "super-2",
    description: "Comprehensive health assessment including liver, kidney, and thyroid functions.",
    price: 1550,
    originalPrice: 2200,
    tests: ["CBC", "LFT", "KFT", "Lipid Profile", "Thyroid Profile", "Blood Sugar", "Vitamin D", "Vitamin B12"],
    testsCount: 60,
    idealFor: "Adults 30–50 years",
    fasting: true,
    reportsIn: "48 hours",
    popular: true,
  },
  {
    id: 3,
    name: "Super 3",
    slug: "super-3",
    description: "Premium package with detailed cardiac, metabolic and hormonal screening.",
    price: 2250,
    originalPrice: 3200,
    tests: ["All from Super 2", "ECG", "HbA1c", "Cardiac Markers", "Iron Studies", "Uric Acid"],
    testsCount: 75,
    idealFor: "Professionals 35+ years",
    fasting: true,
    reportsIn: "48–72 hours",
    popular: true,
  },
  {
    id: 4,
    name: "Super 4",
    slug: "super-4",
    description: "Full-spectrum wellness package with bone health, cardiac, and cancer markers.",
    price: 2550,
    originalPrice: 3800,
    tests: ["All from Super 3", "PSA (Men)/CA-125 (Women)", "Bone Profile", "CRP", "Homocysteine", "Electrolytes"],
    testsCount: 90,
    idealFor: "Adults 45+ years",
    fasting: true,
    reportsIn: "48–72 hours",
    popular: false,
  },
  {
    id: 5,
    name: "Diabetes Care Package",
    slug: "diabetes-care-package",
    description: "Complete diabetes management tests including HbA1c and complications screening.",
    price: 1499,
    originalPrice: 2200,
    tests: ["Blood Sugar Fasting", "Blood Sugar PP", "HbA1c", "KFT", "Urine Microalbumin", "Lipid Profile"],
    testsCount: 45,
    idealFor: "Diabetics & Pre-diabetics",
    fasting: true,
    reportsIn: "24-48 hours",
    popular: true,
  },
  {
    id: 6,
    name: "Women's Health Package",
    slug: "womens-health-package",
    description: "Comprehensive tests for women's health including thyroid and iron levels.",
    price: 1799,
    originalPrice: 2500,
    tests: ["CBC", "Thyroid Profile", "Iron Studies", "Vitamin D", "Vitamin B12", "LFT", "KFT", "Lipid Profile"],
    testsCount: 55,
    idealFor: "Women 25+ years",
    fasting: true,
    reportsIn: "48 hours",
    popular: false,
  },
  {
    id: 7,
    name: "Cardiac Care Package",
    slug: "cardiac-care-package",
    description: "Heart-focused tests for cardiac risk assessment and heart health monitoring.",
    price: 2299,
    originalPrice: 3500,
    tests: ["Lipid Profile Extended", "HsCRP", "Homocysteine", "Lp(a)", "Apo A1, Apo B", "ECG", "CK-MB", "Troponin I"],
    testsCount: 40,
    idealFor: "Heart patients, High-risk individuals",
    fasting: true,
    reportsIn: "24-48 hours",
    popular: false,
  },
  {
    id: 8,
    name: "Fever Panel",
    slug: "fever-panel",
    description: "Tests for common fever causes including dengue, malaria, typhoid, and UTI.",
    price: 1499,
    originalPrice: 2000,
    tests: ["CBC", "Malaria Antigen", "Dengue NS1, IgG, IgM", "Widal", "Urine Routine", "CRP"],
    testsCount: 18,
    idealFor: "Fever patients",
    fasting: false,
    reportsIn: "Same day",
    popular: true,
  },
] as const;

export const WHY_CHOOSE_US = [
  {
    icon: "award",
    title: "NABL Accredited Lab",
    description: "Certified for quality and accuracy following international standards.",
  },
  {
    icon: "clock",
    title: "Quick Reports",
    description: "Get most test results within 24-48 hours via email and WhatsApp.",
  },
  {
    icon: "home",
    title: "Home Collection",
    description: "Free sample collection from your doorstep across Lucknow.",
  },
  {
    icon: "shield",
    title: "Accurate Results",
    description: "State-of-the-art equipment with stringent quality control.",
  },
  {
    icon: "wallet",
    title: "Affordable Pricing",
    description: "Competitive prices with special discounts on health packages.",
  },
  {
    icon: "headset",
    title: "24/7 Support",
    description: "Dedicated customer support for all your queries.",
  },
] as const;

export const TESTIMONIALS = [
  {
    id: 1,
    name: "Rajesh Kumar",
    location: "Gomti Nagar, Lucknow",
    rating: 5,
    text: "Excellent service! The home collection was punctual and the reports came on WhatsApp within 24 hours. Highly recommended.",
    date: "2024-01",
  },
  {
    id: 2,
    name: "Priya Singh",
    location: "Hazratganj, Lucknow",
    rating: 5,
    text: "Very professional staff and clean facility. The doctor explained all my reports clearly. Great experience overall.",
    date: "2024-02",
  },
  {
    id: 3,
    name: "Mohd. Ahmed",
    location: "Aliganj, Lucknow",
    rating: 4,
    text: "Affordable prices compared to other labs. Reports are accurate and detailed. Will use again.",
    date: "2024-01",
  },
  {
    id: 4,
    name: "Sunita Sharma",
    location: "Indiranagar, Lucknow",
    rating: 5,
    text: "The home sample collection for my elderly mother was very convenient. The technician was gentle and caring. Thank you!",
    date: "2024-03",
  },
  {
    id: 5,
    name: "Amit Verma",
    location: "Vikas Nagar, Lucknow",
    rating: 5,
    text: "Best diagnostic center in Lucknow. Quick reports, reasonable prices, and excellent customer service.",
    date: "2024-02",
  },
] as const;

export const FAQS = [
  {
    question: "What are your working hours?",
    answer: "We are open from 7:00 AM to 9:00 PM, Monday to Saturday. On Sundays, we operate from 8:00 AM to 2:00 PM. Home collection timings are flexible and can be scheduled as per your convenience.",
  },
  {
    question: "Do I need to fast before my blood test?",
    answer: "Fasting is required for certain tests like blood sugar (fasting), lipid profile, and some health packages. Usually, 10-12 hours of fasting is recommended. You can drink water during fasting. Our team will inform you about specific requirements when you book your test.",
  },
  {
    question: "How can I get my test reports?",
    answer: "Reports are delivered via email and WhatsApp. You can also download reports from our website using your patient ID. Most routine tests are available within 24-48 hours, while some specialized tests may take 3-5 days.",
  },
  {
    question: "Is home sample collection available?",
    answer: "Yes, we offer free home sample collection across Lucknow. You can book online or call us to schedule a convenient time. Our trained technicians will collect samples from your doorstep with proper safety protocols.",
  },
  {
    question: "What payment methods do you accept?",
    answer: "We accept cash, UPI (Google Pay, PhonePe, Paytm), credit/debit cards, and net banking. For home collection, payment can be made online or in cash to the technician.",
  },
  {
    question: "How accurate are your test results?",
    answer: "Our lab is NABL accredited, which means we follow stringent quality standards. We use state-of-the-art equipment and participate in external quality assurance programs to ensure accurate and reliable results.",
  },
  {
    question: "Can I cancel or reschedule my appointment?",
    answer: "Yes, you can cancel or reschedule your appointment by calling us at least 2 hours before the scheduled time. For home collection, please inform us by the previous day for any changes.",
  },
  {
    question: "Do you offer any discounts on health packages?",
    answer: "Yes, we offer special discounts on health packages, especially during health awareness months. Senior citizens and repeat customers get additional benefits. Check our website or call us for current offers.",
  },
] as const;

export const BLOG_POSTS = [
  {
    id: 1,
    slug: "importance-of-regular-health-checkups",
    title: "The Importance of Regular Health Checkups",
    excerpt: "Regular health checkups can detect diseases early, even before symptoms appear. Learn why annual screenings are essential for maintaining good health.",
    category: "Health Tips",
    date: "2024-03-15",
    readTime: "5 min read",
    image: "https://images.pexels.com/photos/4226140/pexels-photo-4226140.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 2,
    slug: "understanding-your-blood-test-results",
    title: "Understanding Your Blood Test Results",
    excerpt: "Blood tests provide valuable information about your health. This guide explains common blood test parameters and what abnormal values might indicate.",
    category: "Health Education",
    date: "2024-03-10",
    readTime: "8 min read",
    image: "https://images.pexels.com/photos/4226114/pexels-photo-4226114.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 3,
    slug: "diabetes-management-guide",
    title: "Diabetes Management: Tests You Should Know About",
    excerpt: "Managing diabetes requires regular monitoring. Learn about the essential tests for diabetes management and how often you should get them done.",
    category: "Diabetes",
    date: "2024-03-05",
    readTime: "6 min read",
    image: "https://images.pexels.com/photos/4226256/pexels-photo-4226256.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 4,
    slug: "thyroid-health-guide",
    title: "Thyroid Health: Symptoms, Tests, and Treatment",
    excerpt: "Thyroid disorders are common but often go undiagnosed. Understand the symptoms, required tests, and treatment options for thyroid conditions.",
    category: "Thyroid",
    date: "2024-02-28",
    readTime: "7 min read",
    image: "https://images.pexels.com/photos/4226140/pexels-photo-4226140.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 5,
    slug: "preparing-for-blood-tests",
    title: "How to Prepare for Your Blood Test",
    excerpt: "Proper preparation ensures accurate test results. Follow these guidelines to prepare for different types of blood tests correctly.",
    category: "Health Tips",
    date: "2024-02-20",
    readTime: "4 min read",
    image: "https://images.pexels.com/photos/4226114/pexels-photo-4226114.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 6,
    slug: "vitamin-d-deficiency",
    title: "Vitamin D Deficiency: Signs and Solutions",
    excerpt: "Vitamin D deficiency is widespread in India. Learn about its symptoms, health impacts, and how to maintain optimal vitamin D levels.",
    category: "Nutrition",
    date: "2024-02-15",
    readTime: "6 min read",
    image: "https://images.pexels.com/photos/4226256/pexels-photo-4226256.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
] as const;

export const TEST_CATEGORIES = [
  "Hematology",
  "Diabetes",
  "Liver",
  "Kidney",
  "Cardiac",
  "Thyroid",
  "Vitamins",
  "Infectious",
  "Women's Health",
  "Urinary",
  "Digestive",
  "Health Checkup",
] as const;
